const { applyPatch } = await load("src/patch.mjs");
const doc = () => ({ a: 1, b: { c: [1, 2, 3] }, "x/y": 1, "m~n": 2 });
const run = (ops) => applyPatch(doc(), ops);
assert.deepEqual(run([{ op: "add", path: "/d", value: 4 }]), { ...doc(), d: 4 });
assert.deepEqual(run([{ op: "add", path: "/b/c/1", value: 9 }]).b.c, [1, 9, 2, 3]);
assert.deepEqual(run([{ op: "add", path: "/b/c/3", value: 9 }]).b.c, [1, 2, 3, 9]);
assert.deepEqual(run([{ op: "add", path: "/b/c/-", value: 9 }]).b.c, [1, 2, 3, 9]);
assert.deepEqual(run([{ op: "add", path: "/a", value: 5 }]).a, 5);
assert.deepEqual(applyPatch({ a: 1 }, [{ op: "add", path: "", value: [1] }]), [1]);
assert.deepEqual(run([{ op: "remove", path: "/b/c/0" }]).b.c, [2, 3]);
assert.deepEqual(run([{ op: "remove", path: "/a" }]).a, undefined);
assert.deepEqual(run([{ op: "replace", path: "/b/c/2", value: "z" }]).b.c, [1, 2, "z"]);
assert.deepEqual(run([{ op: "replace", path: "/x~1y", value: 7 }])["x/y"], 7);
assert.deepEqual(run([{ op: "replace", path: "/m~0n", value: 7 }])["m~n"], 7);
assert.deepEqual(run([{ op: "move", from: "/b/c/0", path: "/b/c/2" }]).b.c, [2, 3, 1]);
assert.deepEqual(run([{ op: "move", from: "/a", path: "/b/a" }]).b, { c: [1, 2, 3], a: 1 });
const copied = run([{ op: "copy", from: "/b", path: "/e" }]);
copied.e.c.push(4);
assert.deepEqual(copied.b.c, [1, 2, 3]);
assert.deepEqual(run([{ op: "test", path: "/b", value: { c: [1, 2, 3] } }, { op: "add", path: "/t", value: 1 }]).t, 1);
const fails = (ops, re = /^op \d+:/) => assert.throws(() => run(ops), (e) => e instanceof Error && re.test(e.message));
fails([{ op: "test", path: "/a", value: "1" }], /^op 0:/);
fails([{ op: "test", path: "/b", value: { c: [1, 2] } }]);
fails([{ op: "remove", path: "/nope" }]);
fails([{ op: "replace", path: "/nope", value: 1 }]);
fails([{ op: "add", path: "/b/c/4", value: 1 }]);
fails([{ op: "add", path: "/b/c/01", value: 1 }]);
fails([{ op: "add", path: "/b/c/-1", value: 1 }]);
fails([{ op: "remove", path: "/b/c/3" }]);
fails([{ op: "remove", path: "/b/c/-" }]);
fails([{ op: "add", path: "/p/q", value: 1 }]);
fails([{ op: "add", path: "a", value: 1 }]);
fails([{ op: "add", path: "/a~2", value: 1 }]);
fails([{ op: "move", from: "/b", path: "/b/c/0" }]);
fails([{ op: "move", from: "/zzz", path: "/q" }]);
fails([{ op: "remove", path: "" }]);
fails([{ op: "frobnicate", path: "/a" }]);
fails([{ op: "add", path: "/ok", value: 1 }, { op: "add", path: "/ok2", value: 1 }, { op: "remove", path: "/nope" }], /^op 2:/);
const original = doc();
const target = doc();
assert.throws(() => applyPatch(target, [{ op: "add", path: "/b/c/-", value: 9 }, { op: "remove", path: "/nope" }]));
assert.deepEqual(target, original);
const out = applyPatch(target, [{ op: "add", path: "/b/c/-", value: 9 }, { op: "remove", path: "/a" }]);
assert.deepEqual(target, original);
assert.deepEqual(out.b.c, [1, 2, 3, 9]);
const val = { k: [1] };
const out2 = applyPatch({}, [{ op: "add", path: "/v", value: val }]);
out2.v.k.push(2);
assert.deepEqual(val, { k: [1] });
