const { displayName } = await load("src/person.mjs");
const { reportLines } = await load("src/report.mjs");
const { greeting, signature } = await load("src/mail.mjs");
const { csvRow } = await load("src/export.mjs");
const { badgeText } = await load("src/badge.mjs");
const ada = { first: "Ada", middle: "byron", last: "Lovelace", suffix: "Jr.", email: "ada@example.com" };
const plain = { first: "Alan", last: "Turing", email: "alan@example.com" };
const empty = { first: "Grace", middle: "", suffix: "", last: "Hopper", email: "g@example.com" };
const quoted = { first: 'Jo "JJ"', last: "O'Neil", email: 'jo"@example.com' };
const accent = { first: "Zoe", middle: "élan", last: "Q", email: "z@example.com" };
assert.equal(displayName(ada), "Ada B. Lovelace, Jr.");
assert.equal(displayName(plain), "Alan Turing");
assert.equal(displayName(empty), "Grace Hopper");
assert.equal(displayName(accent), "Zoe É. Q");
assert.deepEqual(reportLines([ada, plain]), ["1. Ada B. Lovelace, Jr.", "2. Alan Turing"]);
assert.equal(signature(ada), "-- Ada B. Lovelace, Jr.");
assert.equal(signature(plain), "-- Alan Turing");
assert.equal(signature(empty), "-- Grace Hopper");
assert.equal(csvRow(ada), '"Lovelace, Ada B., Jr.","ada@example.com"');
assert.equal(csvRow(plain), '"Turing, Alan","alan@example.com"');
assert.equal(csvRow(empty), '"Hopper, Grace","g@example.com"');
assert.equal(csvRow(quoted), '"O\'Neil, Jo ""JJ""","jo""@example.com"');
assert.equal(greeting(ada), "Dear Ada,");
assert.equal(badgeText(ada), "A. Lovelace");
