const { loadConfig } = await load("src/index.mjs");
const { deepMerge } = await load("src/merge.mjs");
const { applyEnv } = await load("src/env.mjs");
const cfg = join(dir, "config");
const dev = loadConfig(cfg);
assert.deepEqual(dev, { name: "demo", port: 3000, debug: false, tags: ["a", "b"], db: { host: "localhost", poolSize: 5, options: { ssl: false } }, features: { beta: true, legacy: true } });
const prod = loadConfig(cfg, "production");
assert.deepEqual(prod, { name: "demo", port: 8080, debug: false, tags: ["prod"], db: { host: "db.internal", poolSize: 5, options: { ssl: true } }, features: { beta: true } });
assert.equal(Object.hasOwn(prod.features, "legacy"), false);
assert.deepEqual(loadConfig(cfg, "staging"), dev);
const withEnv = loadConfig(cfg, "production", { APP_PORT: "9090", APP_DEBUG: "true", APP_DB__POOLSIZE: "20", APP_DB__OPTIONS__SSL: "false", APP_TAGS: '["x","y"]', APP_NAME: "other", APP_NEW__THING: "42", OTHER: "ignored", APP_: "ignored" });
assert.deepEqual(withEnv, { name: "other", port: 9090, debug: true, tags: ["x", "y"], db: { host: "db.internal", poolSize: 20, options: { ssl: false } }, features: { beta: true }, new: { thing: "42" } });
assert.throws(() => loadConfig(join(cfg, "missing")), Error);
assert.throws(() => loadConfig(cfg, "production", { APP_PORT: "abc" }), TypeError);
assert.throws(() => loadConfig(cfg, "production", { APP_DEBUG: "yes" }), TypeError);
assert.throws(() => loadConfig(cfg, "production", { APP_TAGS: "x" }), TypeError);
assert.throws(() => loadConfig(cfg, "production", { APP_TAGS: '{"a":1}' }), TypeError);
const a = { x: { y: [1], z: 1 }, keep: 1 };
const b = { x: { y: [2, 3], z: null, w: { v: 1 } }, add: [1] };
const aCopy = structuredClone(a);
const bCopy = structuredClone(b);
const merged = deepMerge(a, b);
assert.deepEqual(merged, { x: { y: [2, 3], w: { v: 1 } }, keep: 1, add: [1] });
assert.deepEqual(a, aCopy);
assert.deepEqual(b, bCopy);
merged.x.w.v = 2;
merged.add.push(2);
merged.x.y.push(9);
assert.deepEqual(b, bCopy);
assert.deepEqual(deepMerge({ a: { b: 1 } }, { a: [1] }), { a: [1] });
assert.deepEqual(deepMerge({ a: [1] }, { a: { b: 1 } }), { a: { b: 1 } });
assert.deepEqual(deepMerge({ a: 1 }, { a: { b: null } }), { a: {} });
const base = { db: { poolSize: 5, host: "h" }, n: 1, on: false, list: [], s: "x" };
const baseCopy = structuredClone(base);
const res = applyEnv(base, { APP_DB__POOLSIZE: "7", APP_DB__HOST: "z", APP_N: "1.5", APP_ON: "true", APP_LIST: "[1]", APP_S: "5", APP_Db__Extra__Deep: "q" });
assert.deepEqual(res, { db: { poolSize: 7, host: "z", extra: { deep: "q" } }, n: 1.5, on: true, list: [1], s: "5" });
assert.deepEqual(base, baseCopy);
assert.throws(() => applyEnv(base, { APP_N: "" }), TypeError);
assert.throws(() => applyEnv(base, { APP_N: "1x" }), TypeError);
assert.deepEqual(applyEnv(base, { APP_N: " 3 " }).n, 3);
