// The 12 Node tasks of the session base-rate study (docs/decisions/session-base-rate.md): starter files, reference and plausible-wrong solutions, hidden verifier bodies.
// A verifier body runs after the prelude in tasks.mjs, with `load(path)` importing a module of the task tree; a failed assert or a crash means the work is wrong.

const PKG_PLAIN = JSON.stringify({ name: "task", private: true, type: "module" }, null, 2) + "\n";
const PKG_TEST = JSON.stringify({ name: "task", private: true, type: "module", scripts: { test: "node --test" } }, null, 2) + "\n";
const stub = (name) => `export function ${name}() {\n  throw new Error("not implemented");\n}\n`;

export const NODE_TASKS = [
  {
    id: "n-clamp",
    kind: "easy",
    lang: "node",
    prompt: "Implement clamp in src/clamp.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# clamp\n\n`clamp(value, min, max)` in `src/clamp.mjs` (named export) returns `value` limited to the range from `min` to `max`.\nIt throws a RangeError when `min` is greater than `max`.\n",
      "src/clamp.mjs": stub("clamp"),
      "test/clamp.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { clamp } from "../src/clamp.mjs";\n\ntest("clamps", () => {\n  assert.equal(clamp(5, 0, 10), 5);\n  assert.equal(clamp(-1, 0, 10), 0);\n  assert.equal(clamp(11, 0, 10), 10);\n  assert.throws(() => clamp(1, 5, 2), RangeError);\n});\n`,
    },
    solution: { "src/clamp.mjs": `export function clamp(value, min, max) {\n  if (min > max) throw new RangeError("min is greater than max");\n  return Math.min(Math.max(value, min), max);\n}\n` },
    wrong: null,
    visible: true,
    verify: `const { clamp } = await load("src/clamp.mjs");\nassert.equal(clamp(5, 0, 10), 5);\nassert.equal(clamp(-5, -3, 3), -3);\nassert.equal(clamp(0, 0, 0), 0);\nassert.equal(clamp(10, 0, 10), 10);\nassert.throws(() => clamp(1, 2, 1), RangeError);\n`,
  },
  {
    id: "n-chunk",
    kind: "easy",
    lang: "node",
    prompt: "Implement chunk in src/chunk.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# chunk\n\n`chunk(array, size)` in `src/chunk.mjs` (named export) splits `array` into arrays of `size` items. The last chunk may be shorter. The input is not modified. It throws a RangeError when `size` is not an integer of at least 1.\n",
      "src/chunk.mjs": stub("chunk"),
      "test/chunk.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { chunk } from "../src/chunk.mjs";\n\ntest("chunks", () => {\n  assert.deepEqual(chunk([1, 2, 3, 4, 5], 2), [[1, 2], [3, 4], [5]]);\n  assert.deepEqual(chunk([], 3), []);\n  assert.throws(() => chunk([1], 0), RangeError);\n});\n`,
    },
    solution: { "src/chunk.mjs": `export function chunk(array, size) {\n  if (!Number.isInteger(size) || size < 1) throw new RangeError("size must be an integer of at least 1");\n  const out = [];\n  for (let i = 0; i < array.length; i += size) out.push(array.slice(i, i + size));\n  return out;\n}\n` },
    wrong: null,
    visible: true,
    verify: `const { chunk } = await load("src/chunk.mjs");\nconst input = [1, 2, 3, 4, 5, 6, 7];\nassert.deepEqual(chunk(input, 3), [[1, 2, 3], [4, 5, 6], [7]]);\nassert.deepEqual(input, [1, 2, 3, 4, 5, 6, 7]);\nassert.deepEqual(chunk([1, 2], 5), [[1, 2]]);\nassert.deepEqual(chunk([], 2), []);\nassert.throws(() => chunk([1], 1.5), RangeError);\nassert.throws(() => chunk([1], -1), RangeError);\n`,
  },
  {
    id: "n-unique",
    kind: "easy",
    lang: "node",
    prompt: "Implement unique in src/unique.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# unique\n\n`unique(array)` in `src/unique.mjs` (named export) returns a new array with the duplicates removed. The first occurrence of each value stays, in its original order. Values are compared like `Set` compares them.\n",
      "src/unique.mjs": stub("unique"),
      "test/unique.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { unique } from "../src/unique.mjs";\n\ntest("removes duplicates", () => {\n  assert.deepEqual(unique([3, 1, 3, 2, 1]), [3, 1, 2]);\n  assert.deepEqual(unique([]), []);\n});\n`,
    },
    solution: { "src/unique.mjs": `export function unique(array) {\n  return [...new Set(array)];\n}\n` },
    wrong: null,
    visible: true,
    verify: `const { unique } = await load("src/unique.mjs");\nassert.deepEqual(unique(["b", "a", "b", "c", "a"]), ["b", "a", "c"]);\nassert.deepEqual(unique([NaN, NaN, 0, -0]), [NaN, 0]);\nconst input = [1, 1, 2];\nunique(input);\nassert.deepEqual(input, [1, 1, 2]);\n`,
  },
  {
    id: "n-slugify",
    kind: "subtle",
    lang: "node",
    prompt: "Implement slugify in src/slugify.mjs as described in README.md.",
    files: {
      "package.json": PKG_PLAIN,
      "README.md": "# slugify\n\n`slugify(text)` in `src/slugify.mjs` (named export) turns text into a URL slug:\n\n- lower case\n- accented letters are folded to their base letter (`Café` becomes `cafe`)\n- every run of characters that are not a-z or 0-9 becomes one hyphen\n- no hyphen at the start or the end\n- text with nothing usable gives an empty string\n",
      "src/slugify.mjs": stub("slugify"),
    },
    solution: { "src/slugify.mjs": `export function slugify(text) {\n  return text\n    .normalize("NFD")\n    .replace(/[\\u0300-\\u036f]/g, "")\n    .toLowerCase()\n    .replace(/[^a-z0-9]+/g, "-")\n    .replace(/^-+|-+$/g, "");\n}\n` },
    wrong: { "src/slugify.mjs": `export function slugify(text) {\n  return text\n    .toLowerCase()\n    .replace(/[^a-z0-9]+/g, "-")\n    .replace(/^-+|-+$/g, "");\n}\n` },
    visible: false,
    verify: `const { slugify } = await load("src/slugify.mjs");\nassert.equal(slugify("Hello, World!"), "hello-world");\nassert.equal(slugify("  Caf\\u00e9 M\\u00fcnster  "), "cafe-munster");\nassert.equal(slugify("a--b__c"), "a-b-c");\nassert.equal(slugify("!!!"), "");\nassert.equal(slugify("Cr\\u00e8me br\\u00fbl\\u00e9e"), "creme-brulee");\n`,
  },
  {
    id: "n-bytes",
    kind: "subtle",
    lang: "node",
    prompt: "Implement formatBytes in src/bytes.mjs as described in README.md.",
    files: {
      "package.json": PKG_PLAIN,
      "README.md": "# formatBytes\n\n`formatBytes(n)` in `src/bytes.mjs` (named export) formats a byte count for people.\n\n- units are B, KB, MB, GB, TB, each 1024 times the one before; values above the TB range stay in TB\n- below 1024 the result is the number and `B` (`1023 B`)\n- otherwise the value is rounded to one decimal and a trailing `.0` is dropped (`1 KB`, `1.5 KB`)\n- a negative or non-finite `n` throws a RangeError\n",
      "src/bytes.mjs": stub("formatBytes"),
    },
    solution: { "src/bytes.mjs": `const UNITS = ["B", "KB", "MB", "GB", "TB"];\n\nexport function formatBytes(n) {\n  if (!Number.isFinite(n) || n < 0) throw new RangeError("bad byte count");\n  let value = n;\n  let i = 0;\n  while (value >= 1024 && i < UNITS.length - 1) {\n    value /= 1024;\n    i++;\n  }\n  const text = i === 0 ? String(value) : String(Math.round(value * 10) / 10);\n  return \`\${text} \${UNITS[i]}\`;\n}\n` },
    wrong: { "src/bytes.mjs": `const UNITS = ["B", "KB", "MB", "GB", "TB"];\n\nexport function formatBytes(n) {\n  let value = n;\n  let i = 0;\n  while (value >= 1024 && i < UNITS.length - 1) {\n    value /= 1024;\n    i++;\n  }\n  return i === 0 ? \`\${value} B\` : \`\${value.toFixed(1)} \${UNITS[i]}\`;\n}\n` },
    visible: false,
    verify: `const { formatBytes } = await load("src/bytes.mjs");\nassert.equal(formatBytes(0), "0 B");\nassert.equal(formatBytes(1023), "1023 B");\nassert.equal(formatBytes(1024), "1 KB");\nassert.equal(formatBytes(1536), "1.5 KB");\nassert.equal(formatBytes(1048576), "1 MB");\nassert.equal(formatBytes(5 * 1024 ** 4), "5 TB");\nassert.equal(formatBytes(2048 * 1024 ** 4), "2048 TB");\nassert.throws(() => formatBytes(-1), RangeError);\nassert.throws(() => formatBytes(Infinity), RangeError);\n`,
  },
  {
    id: "n-csv",
    kind: "subtle",
    lang: "node",
    prompt: "Implement parseCsvLine in src/csv.mjs as described in README.md.",
    files: {
      "package.json": PKG_PLAIN,
      "README.md": "# parseCsvLine\n\n`parseCsvLine(line)` in `src/csv.mjs` (named export) splits one CSV line into an array of strings.\n\n- fields are separated by commas\n- a field may be wrapped in double quotes; inside quotes a comma is text and `\"\"` is one literal quote\n- spaces outside quotes are kept\n- an empty line gives `['']`\n",
      "src/csv.mjs": stub("parseCsvLine"),
    },
    solution: { "src/csv.mjs": `export function parseCsvLine(line) {\n  const out = [];\n  let cur = "";\n  let quoted = false;\n  for (let i = 0; i < line.length; i++) {\n    const c = line[i];\n    if (quoted) {\n      if (c === '"') {\n        if (line[i + 1] === '"') {\n          cur += '"';\n          i++;\n        } else quoted = false;\n      } else cur += c;\n    } else if (c === '"') quoted = true;\n    else if (c === ",") {\n      out.push(cur);\n      cur = "";\n    } else cur += c;\n  }\n  out.push(cur);\n  return out;\n}\n` },
    wrong: { "src/csv.mjs": `export function parseCsvLine(line) {\n  return line.split(",");\n}\n` },
    visible: false,
    verify: `const { parseCsvLine } = await load("src/csv.mjs");\nassert.deepEqual(parseCsvLine("a,b,c"), ["a", "b", "c"]);\nassert.deepEqual(parseCsvLine('"a,b",c'), ["a,b", "c"]);\nassert.deepEqual(parseCsvLine('"say ""hi""",x'), ['say "hi"', "x"]);\nassert.deepEqual(parseCsvLine(""), [""]);\nassert.deepEqual(parseCsvLine("a,,c"), ["a", "", "c"]);\nassert.deepEqual(parseCsvLine(" a , b "), [" a ", " b "]);\n`,
  },
  {
    id: "n-median",
    kind: "weak",
    lang: "node",
    prompt: "Implement median in src/median.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# median\n\n`median(numbers)` in `src/median.mjs` (named export) returns the median of an array of numbers. With an even count it is the mean of the two middle values. It throws a RangeError on an empty array. The input array is not modified.\n",
      "src/median.mjs": stub("median"),
      "test/median.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { median } from "../src/median.mjs";\n\ntest("median of an odd count", () => {\n  assert.equal(median([3, 1, 2]), 2);\n  assert.equal(median([5]), 5);\n  assert.equal(median([7, 1, 3, 9, 5]), 5);\n});\n`,
    },
    solution: { "src/median.mjs": `export function median(numbers) {\n  if (numbers.length === 0) throw new RangeError("empty input");\n  const sorted = [...numbers].sort((a, b) => a - b);\n  const mid = Math.floor(sorted.length / 2);\n  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;\n}\n` },
    wrong: { "src/median.mjs": `export function median(numbers) {\n  numbers.sort((a, b) => a - b);\n  return numbers[Math.floor(numbers.length / 2)];\n}\n` },
    visible: true,
    verify: `const { median } = await load("src/median.mjs");\nassert.equal(median([4, 1, 3, 2]), 2.5);\nassert.equal(median([1, 2]), 1.5);\nconst input = [9, 1, 5];\nmedian(input);\nassert.deepEqual(input, [9, 1, 5]);\nassert.throws(() => median([]), RangeError);\n`,
  },
  {
    id: "n-leap",
    kind: "weak",
    lang: "node",
    prompt: "Implement isLeapYear in src/leap.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# isLeapYear\n\n`isLeapYear(year)` in `src/leap.mjs` (named export) returns true when `year` is a leap year of the Gregorian calendar.\n",
      "src/leap.mjs": stub("isLeapYear"),
      "test/leap.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { isLeapYear } from "../src/leap.mjs";\n\ntest("some years", () => {\n  assert.equal(isLeapYear(2024), true);\n  assert.equal(isLeapYear(2023), false);\n  assert.equal(isLeapYear(2020), true);\n});\n`,
    },
    solution: { "src/leap.mjs": `export function isLeapYear(year) {\n  return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;\n}\n` },
    wrong: { "src/leap.mjs": `export function isLeapYear(year) {\n  return year % 4 === 0;\n}\n` },
    visible: true,
    verify: `const { isLeapYear } = await load("src/leap.mjs");\nassert.equal(isLeapYear(1900), false);\nassert.equal(isLeapYear(2000), true);\nassert.equal(isLeapYear(2100), false);\nassert.equal(isLeapYear(2400), true);\nassert.equal(isLeapYear(2023), false);\nassert.equal(isLeapYear(2024), true);\n`,
  },
  {
    id: "n-deepequal",
    kind: "weak",
    lang: "node",
    prompt: "Implement deepEqual in src/deep-equal.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# deepEqual\n\n`deepEqual(a, b)` in `src/deep-equal.mjs` (named export) compares two JSON-like values: primitives, arrays and plain objects, nested to any depth.\n\n- the order of object keys does not matter\n- `NaN` equals `NaN`\n- an array never equals an object\n- a property set to `undefined` is not the same as a missing property\n",
      "src/deep-equal.mjs": stub("deepEqual"),
      "test/deep-equal.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { deepEqual } from "../src/deep-equal.mjs";\n\ntest("simple values", () => {\n  assert.equal(deepEqual(1, 1), true);\n  assert.equal(deepEqual("a", "b"), false);\n  assert.equal(deepEqual([1, 2], [1, 2]), true);\n  assert.equal(deepEqual({ a: 1 }, { a: 1 }), true);\n  assert.equal(deepEqual({ a: 1 }, { a: 2 }), false);\n});\n`,
    },
    solution: { "src/deep-equal.mjs": `export function deepEqual(a, b) {\n  if (a === b || (a !== a && b !== b)) return true;\n  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) return false;\n  if (Array.isArray(a) !== Array.isArray(b)) return false;\n  const ka = Object.keys(a);\n  const kb = Object.keys(b);\n  if (ka.length !== kb.length) return false;\n  return ka.every((k) => Object.prototype.hasOwnProperty.call(b, k) && deepEqual(a[k], b[k]));\n}\n` },
    wrong: { "src/deep-equal.mjs": `export function deepEqual(a, b) {\n  return JSON.stringify(a) === JSON.stringify(b);\n}\n` },
    visible: true,
    verify: `const { deepEqual } = await load("src/deep-equal.mjs");\nassert.equal(deepEqual({ a: 1, b: 2 }, { b: 2, a: 1 }), true);\nassert.equal(deepEqual(NaN, NaN), true);\nassert.equal(deepEqual([1, [2]], [1, [3]]), false);\nassert.equal(deepEqual({ a: undefined }, {}), false);\nassert.equal(deepEqual([], {}), false);\nassert.equal(deepEqual({ x: { y: [1, { z: 2 }] } }, { x: { y: [1, { z: 2 }] } }), true);\n`,
  },
  {
    id: "n-retry",
    kind: "notest",
    lang: "node",
    prompt: "Implement retry in src/retry.mjs as described in README.md.",
    files: {
      "package.json": PKG_PLAIN,
      "README.md": "# retry\n\n`retry(fn, attempts)` in `src/retry.mjs` (named export) calls `fn` (sync or async) until it succeeds.\n\n- `attempts` is the total number of calls allowed, the first one included\n- it resolves with the first successful result\n- when every call fails it rejects with the error of the last call\n- an `attempts` that is not an integer of at least 1 rejects with a RangeError\n",
      "src/retry.mjs": stub("retry"),
    },
    solution: { "src/retry.mjs": `export async function retry(fn, attempts) {\n  if (!Number.isInteger(attempts) || attempts < 1) throw new RangeError("attempts must be an integer of at least 1");\n  let last;\n  for (let i = 0; i < attempts; i++) {\n    try {\n      return await fn();\n    } catch (error) {\n      last = error;\n    }\n  }\n  throw last;\n}\n` },
    wrong: { "src/retry.mjs": `export async function retry(fn, attempts) {\n  let last;\n  for (let i = 0; i <= attempts; i++) {\n    try {\n      return await fn();\n    } catch (error) {\n      last = error;\n    }\n  }\n  throw last;\n}\n` },
    visible: false,
    verify: `const { retry } = await load("src/retry.mjs");\nlet calls = 0;\nawait assert.rejects(() => retry(async () => { calls++; throw new Error("e" + calls); }, 3), /e3/);\nassert.equal(calls, 3);\ncalls = 0;\nassert.equal(await retry(async () => { calls++; if (calls < 2) throw new Error("no"); return "ok"; }, 5), "ok");\nassert.equal(calls, 2);\nassert.equal(await retry(() => 7, 1), 7);\nawait assert.rejects(() => retry(() => 1, 0), RangeError);\n`,
  },
  {
    id: "n-lru",
    kind: "notest",
    lang: "node",
    prompt: "Implement LRUCache in src/lru.mjs as described in README.md.",
    files: {
      "package.json": PKG_TEST,
      "README.md": "# LRUCache\n\n`new LRUCache(capacity)` in `src/lru.mjs` (named export) is a least-recently-used cache.\n\n- `get(key)` returns the value or `undefined`, and makes the key the most recently used\n- `set(key, value)` stores the value, new key or existing, and makes the key the most recently used; when the size is then above `capacity` the least recently used key is removed\n- `has(key)` does not change the order\n- `size` is the number of keys held\n- a `capacity` that is not an integer of at least 1 throws a RangeError\n",
      "src/lru.mjs": `export class LRUCache {\n  constructor() {\n    throw new Error("not implemented");\n  }\n}\n`,
      "test/lru.test.mjs": `import assert from "node:assert/strict";\nimport { test } from "node:test";\nimport { LRUCache } from "../src/lru.mjs";\n\ntest("stores and evicts", () => {\n  const cache = new LRUCache(2);\n  cache.set("a", 1);\n  cache.set("b", 2);\n  cache.set("c", 3);\n  assert.equal(cache.has("a"), false);\n  assert.equal(cache.get("c"), 3);\n  assert.equal(cache.size, 2);\n});\n\ntest("get refreshes", () => {\n  const cache = new LRUCache(2);\n  cache.set("a", 1);\n  cache.set("b", 2);\n  cache.get("a");\n  cache.set("c", 3);\n  assert.equal(cache.has("b"), false);\n  assert.equal(cache.has("a"), true);\n});\n\ntest.todo("set on an existing key refreshes it");\n`,
    },
    solution: { "src/lru.mjs": `export class LRUCache {\n  #map = new Map();\n  #capacity;\n\n  constructor(capacity) {\n    if (!Number.isInteger(capacity) || capacity < 1) throw new RangeError("capacity must be an integer of at least 1");\n    this.#capacity = capacity;\n  }\n\n  get size() {\n    return this.#map.size;\n  }\n\n  has(key) {\n    return this.#map.has(key);\n  }\n\n  get(key) {\n    if (!this.#map.has(key)) return undefined;\n    const value = this.#map.get(key);\n    this.#map.delete(key);\n    this.#map.set(key, value);\n    return value;\n  }\n\n  set(key, value) {\n    this.#map.delete(key);\n    this.#map.set(key, value);\n    if (this.#map.size > this.#capacity) this.#map.delete(this.#map.keys().next().value);\n  }\n}\n` },
    wrong: { "src/lru.mjs": `export class LRUCache {\n  #map = new Map();\n  #capacity;\n\n  constructor(capacity) {\n    if (!Number.isInteger(capacity) || capacity < 1) throw new RangeError("capacity must be an integer of at least 1");\n    this.#capacity = capacity;\n  }\n\n  get size() {\n    return this.#map.size;\n  }\n\n  has(key) {\n    return this.#map.has(key);\n  }\n\n  get(key) {\n    if (!this.#map.has(key)) return undefined;\n    const value = this.#map.get(key);\n    this.#map.delete(key);\n    this.#map.set(key, value);\n    return value;\n  }\n\n  set(key, value) {\n    if (this.#map.has(key)) {\n      this.#map.set(key, value);\n      return;\n    }\n    this.#map.set(key, value);\n    if (this.#map.size > this.#capacity) this.#map.delete(this.#map.keys().next().value);\n  }\n}\n` },
    visible: true,
    verify: `const { LRUCache } = await load("src/lru.mjs");\nconst cache = new LRUCache(2);\ncache.set("a", 1);\ncache.set("b", 2);\ncache.set("a", 10);\ncache.set("c", 3);\nassert.equal(cache.has("b"), false);\nassert.equal(cache.get("a"), 10);\nassert.equal(cache.size, 2);\nassert.throws(() => new LRUCache(0), RangeError);\nconst other = new LRUCache(2);\nother.set("x", 1);\nother.set("y", 2);\nother.has("x");\nother.set("z", 3);\nassert.equal(other.has("x"), false);\n`,
  },
  {
    id: "n-price",
    kind: "ambiguous",
    lang: "node",
    prompt: "Implement formatPrice in src/price.mjs. The rules are in docs/FORMAT.md.",
    files: {
      "package.json": PKG_PLAIN,
      "README.md": "# price\n\nHelpers for showing prices. `formatPrice(amount, currency)` lives in `src/price.mjs`; the rules are in `docs/FORMAT.md`.\n",
      "docs/FORMAT.md": "# Price format\n\n`amount` is an integer. For EUR and USD it is in cents, for JPY it is in yen.\n\n- EUR: `12,50 €`. Comma as the decimal mark, a dot between thousands (`1.234,50 €`), a space before the euro sign.\n- USD: `$12.50`. Dot as the decimal mark, a comma between thousands (`$1,234.50`).\n- JPY: `¥1,235`. No decimals, a comma between thousands.\n- A negative amount gets a leading minus sign before everything else (`-$12.50`).\n- Any other currency throws a RangeError.\n",
      "src/price.mjs": stub("formatPrice"),
    },
    solution: { "src/price.mjs": `const group = (digits, sep) => digits.replace(/\\B(?=(\\d{3})+(?!\\d))/g, sep);\n\nexport function formatPrice(amount, currency) {\n  const negative = amount < 0;\n  const abs = Math.abs(amount);\n  const whole = String(Math.floor(abs / 100));\n  const cents = String(abs % 100).padStart(2, "0");\n  let out;\n  if (currency === "EUR") out = \`\${group(whole, ".")},\${cents} €\`;\n  else if (currency === "USD") out = \`$\${group(whole, ",")}.\${cents}\`;\n  else if (currency === "JPY") out = \`¥\${group(String(abs), ",")}\`;\n  else throw new RangeError("unsupported currency");\n  return negative ? "-" + out : out;\n}\n` },
    wrong: { "src/price.mjs": `export function formatPrice(amount, currency) {\n  const value = (amount / 100).toFixed(2);\n  if (currency === "EUR") return value.replace(".", ",") + " €";\n  if (currency === "USD") return "$" + value;\n  if (currency === "JPY") return "¥" + value;\n  throw new RangeError("unsupported currency");\n}\n` },
    visible: false,
    verify: `const { formatPrice } = await load("src/price.mjs");\nassert.equal(formatPrice(1250, "EUR"), "12,50 €");\nassert.equal(formatPrice(123450, "EUR"), "1.234,50 €");\nassert.equal(formatPrice(1250, "USD"), "$12.50");\nassert.equal(formatPrice(123450, "USD"), "$1,234.50");\nassert.equal(formatPrice(1235, "JPY"), "¥1,235");\nassert.equal(formatPrice(-1250, "USD"), "-$12.50");\nassert.equal(formatPrice(-1250, "EUR"), "-12,50 €");\nassert.throws(() => formatPrice(1, "GBP"), RangeError);\n`,
  },
];
