// The 12 Python tasks of the session base-rate study (docs/decisions/session-base-rate.md): starter files, reference and plausible-wrong solutions, hidden verifier bodies.
// Visible tests are stdlib unittest next to the module with a Makefile `test` target; a verifier body runs after the prelude in tasks.mjs, and a failed assert or a crash means the work is wrong.

const MAKEFILE = "test:\n\tpython3 -m unittest -v\n";
const stub = (name) => `def ${name}(*args, **kwargs):\n    raise NotImplementedError\n`;
const testFile = (mod, fn, body) => `import unittest\n\nfrom ${mod} import ${fn}\n\n\nclass Test(unittest.TestCase):\n${body}\n\n\nif __name__ == "__main__":\n    unittest.main()\n`;

export const PYTHON_TASKS = [
  {
    id: "p-wordcount",
    kind: "easy",
    lang: "python",
    prompt: "Implement word_count in textutil.py as described in README.md.",
    files: {
      "README.md": "# word_count\n\n`word_count(text)` in `textutil.py` returns a dict that maps each word to how often it occurs. A word is a maximal run of ASCII letters and digits; the comparison ignores case and the keys are lower case.\n",
      "textutil.py": stub("word_count"),
      "test_textutil.py": testFile("textutil", "word_count", `    def test_counts(self):\n        self.assertEqual(word_count("a b a"), {"a": 2, "b": 1})\n        self.assertEqual(word_count("The the THE"), {"the": 3})\n        self.assertEqual(word_count(""), {})\n`),
      Makefile: MAKEFILE,
    },
    solution: { "textutil.py": `import re\nfrom collections import Counter\n\n\ndef word_count(text):\n    return dict(Counter(re.findall(r"[a-z0-9]+", text.lower())))\n` },
    wrong: null,
    visible: true,
    verify: `from textutil import word_count\nassert word_count("Hello, hello world!") == {"hello": 2, "world": 1}\nassert word_count("don't") == {"don": 1, "t": 1}\nassert word_count("a1 A1 b2") == {"a1": 2, "b2": 1}\nassert word_count("  ...  ") == {}\n`,
  },
  {
    id: "p-fizzbuzz",
    kind: "easy",
    lang: "python",
    prompt: "Implement fizzbuzz in fizz.py as described in README.md.",
    files: {
      "README.md": "# fizzbuzz\n\n`fizzbuzz(n)` in `fizz.py` returns a list of strings for the numbers 1 to n: `Fizz` for multiples of 3, `Buzz` for multiples of 5, `FizzBuzz` for multiples of both, otherwise the number as text. For n below 1 it returns an empty list.\n",
      "fizz.py": stub("fizzbuzz"),
      "test_fizz.py": testFile("fizz", "fizzbuzz", `    def test_small(self):\n        self.assertEqual(fizzbuzz(5), ["1", "2", "Fizz", "4", "Buzz"])\n        self.assertEqual(fizzbuzz(0), [])\n`),
      Makefile: MAKEFILE,
    },
    solution: { "fizz.py": `def fizzbuzz(n):\n    out = []\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            out.append("FizzBuzz")\n        elif i % 3 == 0:\n            out.append("Fizz")\n        elif i % 5 == 0:\n            out.append("Buzz")\n        else:\n            out.append(str(i))\n    return out\n` },
    wrong: null,
    visible: true,
    verify: `from fizz import fizzbuzz\nr = fizzbuzz(15)\nassert r[14] == "FizzBuzz" and r[2] == "Fizz" and r[4] == "Buzz" and r[0] == "1"\nassert len(r) == 15\nassert fizzbuzz(-3) == []\nassert fizzbuzz(30)[29] == "FizzBuzz"\n`,
  },
  {
    id: "p-palindrome",
    kind: "easy",
    lang: "python",
    prompt: "Implement is_palindrome in pal.py as described in README.md.",
    files: {
      "README.md": "# is_palindrome\n\n`is_palindrome(s)` in `pal.py` returns True when `s` reads the same forwards and backwards, ignoring case and every character that is not a letter or a digit. An empty string is a palindrome.\n",
      "pal.py": stub("is_palindrome"),
      "test_pal.py": testFile("pal", "is_palindrome", `    def test_basic(self):\n        self.assertTrue(is_palindrome("Racecar"))\n        self.assertFalse(is_palindrome("hello"))\n        self.assertTrue(is_palindrome(""))\n`),
      Makefile: MAKEFILE,
    },
    solution: { "pal.py": `def is_palindrome(s):\n    cleaned = [c.lower() for c in s if c.isalnum()]\n    return cleaned == cleaned[::-1]\n` },
    wrong: null,
    visible: true,
    verify: `from pal import is_palindrome\nassert is_palindrome("A man, a plan, a canal: Panama")\nassert not is_palindrome("race a car")\nassert is_palindrome("   ")\nassert is_palindrome("12321")\nassert not is_palindrome("12345")\n`,
  },
  {
    id: "p-duration",
    kind: "subtle",
    lang: "python",
    prompt: "Implement parse_duration in duration.py as described in README.md.",
    files: {
      "README.md": "# parse_duration\n\n`parse_duration(text)` in `duration.py` returns the length of a duration string in whole seconds.\n\n- units are `d` (86400 s), `h` (3600 s), `m` (60 s) and `s`\n- a string is one or more parts of a number and a unit, with optional spaces: `1h30m`, `2d 3h`, `90s`, `1h 30 m`\n- the same unit twice, a number without a unit, an unknown unit, an empty string or anything else raises ValueError\n",
      "duration.py": stub("parse_duration"),
    },
    solution: { "duration.py": `import re\n\nUNITS = {"d": 86400, "h": 3600, "m": 60, "s": 1}\n\n\ndef parse_duration(text):\n    if not re.fullmatch(r"(?:\\s*\\d+\\s*[dhms])+\\s*", text):\n        raise ValueError("bad duration")\n    parts = re.findall(r"(\\d+)\\s*([dhms])", text)\n    units = [u for _, u in parts]\n    if len(set(units)) != len(units):\n        raise ValueError("repeated unit")\n    return sum(int(n) * UNITS[u] for n, u in parts)\n` },
    wrong: { "duration.py": `import re\n\nUNITS = {"d": 86400, "h": 3600, "m": 60, "s": 1}\n\n\ndef parse_duration(text):\n    return sum(int(n) * UNITS[u] for n, u in re.findall(r"(\\d+)\\s*([dhms])", text))\n` },
    visible: false,
    verify: `from duration import parse_duration\nassert parse_duration("1h30m") == 5400\nassert parse_duration("2d 3h") == 183600\nassert parse_duration("90s") == 90\nassert parse_duration("1h 30 m") == 5400\nfor bad in ["", "90", "5x", "1h1h", "abc", "1h 30"]:\n    try:\n        parse_duration(bad)\n    except ValueError:\n        continue\n    raise AssertionError("no ValueError for " + repr(bad))\n`,
  },
  {
    id: "p-intervals",
    kind: "subtle",
    lang: "python",
    prompt: "Implement merge_intervals in intervals.py as described in README.md.",
    files: {
      "README.md": "# merge_intervals\n\n`merge_intervals(intervals)` in `intervals.py` takes a list of `[start, end]` pairs in any order and returns a new list of merged pairs sorted by start.\n\n- overlapping pairs are merged, and so are pairs that only touch (`[1, 2]` and `[2, 3]` give `[1, 3]`)\n- the input list and its pairs are not modified\n",
      "intervals.py": stub("merge_intervals"),
    },
    solution: { "intervals.py": `def merge_intervals(intervals):\n    out = []\n    for start, end in sorted([a, b] for a, b in intervals):\n        if out and start <= out[-1][1]:\n            out[-1][1] = max(out[-1][1], end)\n        else:\n            out.append([start, end])\n    return out\n` },
    wrong: { "intervals.py": `def merge_intervals(intervals):\n    intervals.sort()\n    out = []\n    for start, end in intervals:\n        if out and start < out[-1][1]:\n            out[-1][1] = max(out[-1][1], end)\n        else:\n            out.append([start, end])\n    return out\n` },
    visible: false,
    verify: `from intervals import merge_intervals\nassert merge_intervals([[1, 3], [2, 6], [8, 10]]) == [[1, 6], [8, 10]]\nassert merge_intervals([[1, 2], [2, 3]]) == [[1, 3]]\nassert merge_intervals([[8, 10], [1, 3]]) == [[1, 3], [8, 10]]\nassert merge_intervals([[1, 10], [2, 3]]) == [[1, 10]]\nassert merge_intervals([]) == []\ndata = [[5, 6], [1, 2]]\nmerge_intervals(data)\nassert data == [[5, 6], [1, 2]]\n`,
  },
  {
    id: "p-titlecase",
    kind: "subtle",
    lang: "python",
    prompt: "Implement title_case in titles.py as described in README.md.",
    files: {
      "README.md": "# title_case\n\n`title_case(text)` in `titles.py` capitalises a title.\n\n- words are separated by single spaces; every other character of a word is lower-cased\n- the small words `a`, `an`, `and`, `the`, `of`, `in`, `on`, `to`, `or` stay lower case, unless they are the first or the last word\n- each part of a hyphenated word is capitalised (`state-of-the-art` becomes `State-Of-The-Art`)\n",
      "titles.py": stub("title_case"),
    },
    solution: { "titles.py": `SMALL = {"a", "an", "and", "the", "of", "in", "on", "to", "or"}\n\n\ndef title_case(text):\n    words = text.split(" ")\n    out = []\n    for i, word in enumerate(words):\n        lower = word.lower()\n        if 0 < i < len(words) - 1 and lower in SMALL:\n            out.append(lower)\n        else:\n            out.append("-".join(p[:1].upper() + p[1:] for p in lower.split("-")))\n    return " ".join(out)\n` },
    wrong: { "titles.py": `def title_case(text):\n    return text.title()\n` },
    visible: false,
    verify: `from titles import title_case\nassert title_case("the lord of the rings") == "The Lord of the Rings"\nassert title_case("state-of-the-art design") == "State-Of-The-Art Design"\nassert title_case("war and peace") == "War and Peace"\nassert title_case("what to expect in") == "What to Expect In"\nassert title_case("DON'T PANIC") == "Don't Panic"\nassert title_case("") == ""\n`,
  },
  {
    id: "p-dedupe",
    kind: "weak",
    lang: "python",
    prompt: "Implement dedupe in dedupe.py as described in README.md.",
    files: {
      "README.md": "# dedupe\n\n`dedupe(items)` in `dedupe.py` returns a new list without duplicates. The first occurrence of each item stays, in its original order. Items are hashable.\n",
      "dedupe.py": stub("dedupe"),
      "test_dedupe.py": testFile("dedupe", "dedupe", `    def test_basic(self):\n        self.assertEqual(dedupe([1, 1, 2, 3, 3]), [1, 2, 3])\n        self.assertEqual(dedupe([]), [])\n        self.assertEqual(dedupe([5]), [5])\n`),
      Makefile: MAKEFILE,
    },
    solution: { "dedupe.py": `def dedupe(items):\n    seen = set()\n    out = []\n    for item in items:\n        if item not in seen:\n            seen.add(item)\n            out.append(item)\n    return out\n` },
    wrong: { "dedupe.py": `def dedupe(items):\n    return list(set(items))\n` },
    visible: true,
    verify: `from dedupe import dedupe\nassert dedupe([3, 1, 3, 2, 1]) == [3, 1, 2]\nassert dedupe(["b", "a", "b"]) == ["b", "a"]\nassert dedupe([9, 8, 7, 9]) == [9, 8, 7]\ndata = [2, 2, 1]\ndedupe(data)\nassert data == [2, 2, 1]\n`,
  },
  {
    id: "p-roman",
    kind: "weak",
    lang: "python",
    prompt: "Implement roman_to_int in roman.py as described in README.md.",
    files: {
      "README.md": "# roman_to_int\n\n`roman_to_int(s)` in `roman.py` converts a Roman numeral (upper case, 1 to 3999) to an int. Subtractive pairs such as `IV`, `IX`, `XL`, `XC`, `CD` and `CM` are supported.\n",
      "roman.py": stub("roman_to_int"),
      "test_roman.py": testFile("roman", "roman_to_int", `    def test_additive(self):\n        self.assertEqual(roman_to_int("III"), 3)\n        self.assertEqual(roman_to_int("VIII"), 8)\n        self.assertEqual(roman_to_int("XII"), 12)\n`),
      Makefile: MAKEFILE,
    },
    solution: { "roman.py": `VALUES = {"I": 1, "V": 5, "X": 10, "L": 50, "C": 100, "D": 500, "M": 1000}\n\n\ndef roman_to_int(s):\n    total = 0\n    for i, ch in enumerate(s):\n        value = VALUES[ch]\n        if i + 1 < len(s) and VALUES[s[i + 1]] > value:\n            total -= value\n        else:\n            total += value\n    return total\n` },
    wrong: { "roman.py": `VALUES = {"I": 1, "V": 5, "X": 10, "L": 50, "C": 100, "D": 500, "M": 1000}\n\n\ndef roman_to_int(s):\n    return sum(VALUES[ch] for ch in s)\n` },
    visible: true,
    verify: `from roman import roman_to_int\nassert roman_to_int("IV") == 4\nassert roman_to_int("IX") == 9\nassert roman_to_int("XLII") == 42\nassert roman_to_int("MCMXCIV") == 1994\nassert roman_to_int("MMXXIV") == 2024\nassert roman_to_int("III") == 3\n`,
  },
  {
    id: "p-flatten",
    kind: "weak",
    lang: "python",
    prompt: "Implement flatten in flat.py as described in README.md.",
    files: {
      "README.md": "# flatten\n\n`flatten(nested)` in `flat.py` returns a new flat list from lists nested to any depth. Only lists are opened: a string stays one item.\n",
      "flat.py": stub("flatten"),
      "test_flat.py": testFile("flat", "flatten", `    def test_one_level(self):\n        self.assertEqual(flatten([1, [2, 3], 4]), [1, 2, 3, 4])\n        self.assertEqual(flatten([]), [])\n`),
      Makefile: MAKEFILE,
    },
    solution: { "flat.py": `def flatten(nested):\n    out = []\n    for item in nested:\n        if isinstance(item, list):\n            out.extend(flatten(item))\n        else:\n            out.append(item)\n    return out\n` },
    wrong: { "flat.py": `def flatten(nested):\n    return [y for x in nested for y in (x if isinstance(x, list) else [x])]\n` },
    visible: true,
    verify: `from flat import flatten\nassert flatten([1, [2, [3, [4]]]]) == [1, 2, 3, 4]\nassert flatten(["ab", ["cd"]]) == ["ab", "cd"]\nassert flatten([[], [[]]]) == []\nassert flatten([1, 2]) == [1, 2]\n`,
  },
  {
    id: "p-ratelimit",
    kind: "notest",
    lang: "python",
    prompt: "Implement RateLimiter in ratelimit.py as described in README.md.",
    files: {
      "README.md": "# RateLimiter\n\n`RateLimiter(max_calls, period, clock=time.monotonic)` in `ratelimit.py` limits calls in a sliding window.\n\n- `allow()` returns True and records the call when fewer than `max_calls` allowed calls happened in the last `period` seconds; otherwise it returns False and records nothing\n- a call made at time `t` stops counting at `t + period`\n- `clock` is a function that returns the current time in seconds; tests pass a fake one\n",
      "ratelimit.py": `class RateLimiter:\n    def __init__(self, *args, **kwargs):\n        raise NotImplementedError\n`,
    },
    solution: { "ratelimit.py": `import time\nfrom collections import deque\n\n\nclass RateLimiter:\n    def __init__(self, max_calls, period, clock=time.monotonic):\n        self.max_calls = max_calls\n        self.period = period\n        self.clock = clock\n        self.calls = deque()\n\n    def allow(self):\n        now = self.clock()\n        while self.calls and self.calls[0] <= now - self.period:\n            self.calls.popleft()\n        if len(self.calls) < self.max_calls:\n            self.calls.append(now)\n            return True\n        return False\n` },
    wrong: { "ratelimit.py": `import time\n\n\nclass RateLimiter:\n    def __init__(self, max_calls, period, clock=time.monotonic):\n        self.max_calls = max_calls\n        self.period = period\n        self.clock = clock\n        self.window_start = None\n        self.count = 0\n\n    def allow(self):\n        now = self.clock()\n        if self.window_start is None or now - self.window_start >= self.period:\n            self.window_start = now\n            self.count = 0\n        if self.count < self.max_calls:\n            self.count += 1\n            return True\n        return False\n` },
    visible: false,
    verify: `from ratelimit import RateLimiter\nnow = [0.0]\nlimiter = RateLimiter(2, 10, clock=lambda: now[0])\nassert limiter.allow()\nnow[0] = 5\nassert limiter.allow()\nnow[0] = 6\nassert not limiter.allow()\nnow[0] = 10\nassert limiter.allow()\nnow[0] = 11\nassert not limiter.allow()\nnow[0] = 15\nassert limiter.allow()\n`,
  },
  {
    id: "p-phone",
    kind: "ambiguous",
    lang: "python",
    prompt: "Implement normalize_phone in phone.py. The rules are in README.md.",
    files: {
      "README.md": "# normalize_phone\n\n`normalize_phone(text)` in `phone.py` turns a German phone number into E.164 form.\n\n1. Remove spaces, dashes, slashes and parentheses.\n2. A leading `00` becomes `+`.\n3. A leading single `0` becomes `+49`.\n4. A number that already starts with `+` stays as it is, but a trunk zero right after the country code, written `+49 (0) 30 ...`, is dropped.\n5. The result must be `+` followed by 8 to 15 digits, otherwise ValueError is raised.\n",
      "phone.py": stub("normalize_phone"),
    },
    solution: { "phone.py": `import re\n\n\ndef normalize_phone(text):\n    s = text.strip()\n    s = re.sub(r"\\+49\\s*\\(0\\)", "+49", s)\n    s = re.sub(r"[\\s\\-/()]", "", s)\n    if s.startswith("00"):\n        s = "+" + s[2:]\n    elif s.startswith("0"):\n        s = "+49" + s[1:]\n    if not re.fullmatch(r"\\+\\d{8,15}", s):\n        raise ValueError("not a phone number")\n    return s\n` },
    wrong: { "phone.py": `import re\n\n\ndef normalize_phone(text):\n    s = re.sub(r"[\\s\\-/()]", "", text)\n    if s.startswith("00"):\n        s = "+" + s[2:]\n    elif s.startswith("0"):\n        s = "+49" + s[1:]\n    if not re.fullmatch(r"\\+\\d{8,15}", s):\n        raise ValueError("not a phone number")\n    return s\n` },
    visible: false,
    verify: `from phone import normalize_phone\nassert normalize_phone("030 1234567") == "+49301234567"\nassert normalize_phone("0049 30 1234567") == "+49301234567"\nassert normalize_phone("(030) 12 34 567") == "+49301234567"\nassert normalize_phone("030/1234-567") == "+49301234567"\nassert normalize_phone("+49 (0) 30 1234567") == "+49301234567"\nassert normalize_phone("+44 20 7946 0958") == "+442079460958"\nfor bad in ["12", "abc", "+1"]:\n    try:\n        normalize_phone(bad)\n    except ValueError:\n        continue\n    raise AssertionError("no ValueError for " + repr(bad))\n`,
  },
  {
    id: "p-bizday",
    kind: "ambiguous",
    lang: "python",
    prompt: "Implement next_business_day in bizday.py. The rules are in README.md.",
    files: {
      "README.md": "# next_business_day\n\n`next_business_day(day)` in `bizday.py` takes a `datetime.date` and returns the next business day after it.\n\n- Saturdays and Sundays are not business days\n- neither are the dates in `holidays.txt` next to the module: one ISO date (`YYYY-MM-DD`) per line, blank lines and lines starting with `#` ignored\n",
      "holidays.txt": "# company holidays\n2026-12-24\n2026-12-25\n\n2027-01-01\n",
      "bizday.py": stub("next_business_day"),
    },
    solution: { "bizday.py": `import os\nfrom datetime import date, timedelta\n\n\ndef _holidays():\n    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "holidays.txt")\n    out = set()\n    with open(path) as handle:\n        for line in handle:\n            line = line.strip()\n            if line and not line.startswith("#"):\n                out.add(date.fromisoformat(line))\n    return out\n\n\ndef next_business_day(day):\n    holidays = _holidays()\n    current = day + timedelta(days=1)\n    while current.weekday() >= 5 or current in holidays:\n        current += timedelta(days=1)\n    return current\n` },
    wrong: { "bizday.py": `from datetime import timedelta\n\n\ndef next_business_day(day):\n    current = day + timedelta(days=1)\n    while current.weekday() >= 5:\n        current += timedelta(days=1)\n    return current\n` },
    visible: false,
    verify: `from datetime import date\nfrom bizday import next_business_day\nassert next_business_day(date(2026, 12, 23)) == date(2026, 12, 28)\nassert next_business_day(date(2026, 10, 1)) == date(2026, 10, 2)\nassert next_business_day(date(2026, 10, 2)) == date(2026, 10, 5)\nassert next_business_day(date(2026, 12, 31)) == date(2027, 1, 4)\n`,
  },
];
