// Builds the GitHub social preview: node build-social.mjs
// Writes a self-contained social-preview.html (fonts as base64 woff2, mark and wordmark as SVG paths),
// renders it with Playwright's Chromium to ../assets/social-preview.png at 1280 x 640
// and checks size, dimensions and the safe area.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { THEMES, mix } from "./lib/tokens.mjs";
import { markSVG, wordmarkSVG } from "./lib/brand.mjs";
import { launch } from "./render-previews.mjs";
const here = path.dirname(fileURLToPath(import.meta.url));
const HTML = path.join(here, "social-preview.html");
const PNG = path.join(here, "..", "assets", "social-preview.png");
const W = 1280, H = 640, SAFE = 64;
const t = THEMES.dark;
const b64 = (pkg, file) => fs.readFileSync(path.join(here, "node_modules", "@fontsource", pkg, "files", file)).toString("base64");
const face = (family, weight, pkg, file) => `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${b64(pkg, file)}) format("woff2")}`;
function lockup() {
  const size = 96, capH = 64, gap = 26;
  const mark = markSVG({ x: 0, y: 0, size, bg: t.accent, fg: t.onAccent });
  const wm = wordmarkSVG({ x: size + gap, top: (size - capH) / 2 - 5, capHeight: capH, fill: t.text, fillHead: t.secondary });
  const w = Math.ceil(size + gap + wm.width + 2);
  return `<svg class="lockup" xmlns="http://www.w3.org/2000/svg" width="${w}" height="${size}" viewBox="0 0 ${w} ${size}" role="img" aria-label="claude-referee">${mark}${wm.svg}</svg>`;
}
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=${W}">
<title>claude-referee social preview (1280 x 640)</title>
<!-- Generated by build-social.mjs. Fonts: Inter and JetBrains Mono (SIL OFL 1.1) via @fontsource. -->
<style>
${face("Inter", 400, "inter", "inter-latin-400-normal.woff2")}
${face("Inter", 600, "inter", "inter-latin-600-normal.woff2")}
${face("JetBrains Mono", 400, "jetbrains-mono", "jetbrains-mono-latin-400-normal.woff2")}
:root{--page:${t.page};--raised:${t.raised};--border:${t.border};--text:${t.text};--secondary:${t.secondary};--accent:${t.accent};
  --band:${mix(t.accent, t.raised, 0.13)}}
*{box-sizing:border-box}
html,body{margin:0;width:${W}px;height:${H}px;background:var(--page);overflow:hidden}
body{font-family:"Inter",sans-serif;color:var(--text);-webkit-font-smoothing:antialiased}
.frame{width:${W}px;height:${H}px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}
.lockup{display:block}
.tagline{margin:40px 0 0;font-size:52px;font-weight:600;letter-spacing:-0.02em;line-height:1.1}
.features{margin:16px 0 0;font-size:26px;color:var(--secondary);letter-spacing:-0.005em}
.card{margin:40px 0 0;padding:14px 12px;background:var(--raised);border:1px solid var(--border);border-radius:14px;
  font-family:"JetBrains Mono",monospace;font-size:20px;line-height:1;text-align:left}
.row{display:grid;grid-template-columns:22px 9ch auto;align-items:center;padding:12px 26px 12px 14px;border-radius:9px;white-space:pre}
.row.ref{background:var(--band);box-shadow:inset 3px 0 0 var(--accent);color:var(--accent)}
.who{color:var(--secondary)}.ref .who{color:var(--accent)}
.b{width:9px;height:9px;border-radius:50%;background:var(--secondary)}
.ref .b{width:10px;height:10px;border-radius:1px;transform:rotate(45deg);background:var(--accent)}
.foot{margin:44px 0 0;font-size:19px;color:var(--secondary);letter-spacing:0.01em}
</style>
</head>
<body>
<main class="frame">
  ${lockup()}
  <h1 class="tagline">Evidence over eloquence.</h1>
  <p class="features">Claude makes the big calls. The referee makes the small ones.</p>
  <div class="card" aria-label="Transcript">
    <div class="row"><span class="b"></span><span class="who">claude</span><span>All tests pass. Done.</span></div>
    <div class="row ref"><span class="b"></span><span class="who">referee</span><span>No passing check since your last edit.</span></div>
  </div>
  <p class="foot">unofficial · built on TypeSafe Jev · MIT</p>
</main>
</body>
</html>
`;
fs.writeFileSync(HTML, html);
console.log(`wrote assets-src/social-preview.html (${(fs.statSync(HTML).size / 1024).toFixed(1)} KB)`);
const browser = await launch();
const page = await browser.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 1 });
await page.goto("file://" + HTML);
await page.evaluate(() => document.fonts.ready);
const boxes = await page.evaluate(() => [...document.querySelectorAll(".frame > *")].map((e) => {
  const r = e.getBoundingClientRect();
  return { el: e.className.baseVal ?? e.className, x1: r.left, y1: r.top, x2: r.right, y2: r.bottom };
}));
const fontsOk = await page.evaluate(() => ["400 20px Inter", "600 20px Inter", '400 20px "JetBrains Mono"'].every((f) => document.fonts.check(f)));
await page.screenshot({ path: PNG, clip: { x: 0, y: 0, width: W, height: H } });
await browser.close();
let bad = 0;
for (const b of boxes) {
  const inside = b.x1 >= SAFE && b.y1 >= SAFE && b.x2 <= W - SAFE && b.y2 <= H - SAFE;
  if (!inside) bad++;
  console.log(`  ${inside ? "ok " : "OUT"} ${String(b.el).padEnd(10)} x ${b.x1.toFixed(0)}-${b.x2.toFixed(0)}  y ${b.y1.toFixed(0)}-${b.y2.toFixed(0)}`);
}
const png = fs.readFileSync(PNG);
const pw = png.readUInt32BE(16), ph = png.readUInt32BE(20);
console.log(`wrote assets/social-preview.png ${pw}x${ph}, ${(png.length / 1024).toFixed(1)} KB; embedded fonts loaded: ${fontsOk}`);
if (bad || pw !== W || ph !== H || png.length >= 1024 * 1024 || !fontsOk) {
  console.error("social preview check FAILED");
  process.exit(1);
}
