const { render } = await load("src/render.mjs");
const r = render;
assert.equal(r("Hello {{name}}!", { name: "Ada" }), "Hello Ada!");
assert.equal(r("{{ name }}", { name: "Ada" }), "Ada");
assert.equal(r("{{x}}", { x: `<a href="x">&'</a>` }), "&lt;a href=&quot;x&quot;&gt;&amp;&#39;&lt;/a&gt;");
assert.equal(r("{{{x}}}", { x: "<b>&</b>" }), "<b>&</b>");
assert.equal(r("{{a.b.c}}", { a: { b: { c: 7 } } }), "7");
assert.equal(r("{{items.1.n}}", { items: [{ n: "x" }, { n: "y" }] }), "y");
assert.equal(r("[{{a.b.c}}]", { a: {} }), "[]");
assert.equal(r("[{{x}}][{{y}}][{{z}}]", { x: null, y: undefined }), "[][][]");
assert.equal(r("{{n}} {{f}} {{e}}", { n: 0, f: false, e: "" }), "0 false ");
assert.equal(r("[{{constructor}}][{{toString}}][{{a.constructor}}]", { a: {} }), "[][][]");
assert.equal(r("{{#if x}}yes{{/if}}", { x: true }), "yes");
for (const falsy of [false, null, undefined, 0, NaN, "", []]) assert.equal(r("{{#if x}}yes{{else}}no{{/if}}", { x: falsy }), "no", String(falsy));
for (const truthy of ["0", {}, [0], 1, "a", true]) assert.equal(r("{{#if x}}yes{{else}}no{{/if}}", { x: truthy }), "yes", String(truthy));
assert.equal(r("{{#if missing}}yes{{else}}no{{/if}}", {}), "no");
assert.equal(r("{{#each xs}}<{{this}}:{{@index}}>{{/each}}", { xs: ["a", "b"] }), "<a:0><b:1>");
assert.equal(r("{{#each xs}}x{{/each}}|", { xs: [] }), "|");
assert.equal(r("{{#each xs}}x{{/each}}|", { xs: "abc" }), "|");
assert.equal(r("{{#each xs}}x{{/each}}|", {}), "|");
assert.equal(r("{{#each users}}{{name}}={{title}};{{/each}}", { title: "T", users: [{ name: "a" }, { name: "b", title: "B" }] }), "a=T;b=B;");
assert.equal(r("{{#each rows}}{{#each this}}{{this}}{{/each}}/{{/each}}", { rows: [[1, 2], [3]] }), "12/3/");
assert.equal(r("{{#each rows}}{{#each cells}}{{@index}}{{this.v}}{{/each}}|{{@index}};{{/each}}", { rows: [{ cells: [{ v: "a" }, { v: "b" }] }, { cells: [{ v: "c" }] }] }), "0a1b|0;0c|1;");
assert.equal(r("{{#each xs}}{{#if this}}{{this}}{{else}}-{{/if}}{{/each}}", { xs: [1, 0, 2, "", []] }), "1-2--");
assert.equal(r("{{#each xs}}{{this.name}}{{/each}}", { name: "outer", xs: [{ name: "inner" }, {}] }), "inner");
assert.equal(r("\\{{name}} and {{name}}", { name: "x" }), "{{name}} and x");
assert.equal(r("a\\{{{b}}}c", { b: 1 }), "a{{{b}}}c");
assert.equal(r("{{#if a}}{{#if b}}ab{{else}}a{{/if}}{{else}}none{{/if}}", { a: 1, b: 0 }), "a");
for (const bad of ["{{#if x}}", "{{/if}}", "{{#each x}}{{/if}}", "{{#while x}}{{/while}}", "{{else}}", "{{#if x}}{{else}}{{else}}{{/if}}"]) assert.throws(() => r(bad, {}), SyntaxError, bad);
